### ISSUE TITLE
Crash issue when clicking mod description still present

### ISSUE THREAD

**Issue by jacobthefailure** [lazynessmind/Snad#5]
The issue is still present in the latest Curse build, and despite the filename being 'snad-1.8.4.22a-1.15.2.jar', it reports ingame as 1.8.3.3a.

_Originally posted by @jacobthefailure in https://github.com/lazynessmind/Snad/issues/4#issuecomment-608471458_

**Comment by lazynessmind** [comment]
I could not reproduce the problem, but I made some changes that probably will fix it. Thanks for the help.
