### ISSUE TITLE
Clicking on Snad in Mod List crashes the game

### ISSUE THREAD

**Issue by Sunekaer** [lazynessmind/Snad#7]
Modpack: FTB Omnia
Forge version 31.1.87
Minecraft version 1.15.2

https://paste.sunekaer.com/ujifeyizod.rb
https://paste.feed-the-beast.com/view/5787eaa3

**Comment by lazynessmind** [comment]
![imagem](https://user-images.githubusercontent.com/52864251/82434050-3d21a180-9a8a-11ea-947a-0878f531c82e.png)

This one again. Working on it

**Comment by lazynessmind** [comment]
Now it is actually fixed!
