### ISSUE TITLE
Cactus farm broken

### ISSUE THREAD

**Issue by GuyASmith** [lazynessmind/Snad#8]
So I have an old-reliable style cactus farm that has cacti on snad and next to the air block above are glass panes so the cactus pops off. It crashed, I'm guessing because of the hack to allow the cactus to grow upward as far as possible.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/17/20 2:49 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:classloading}
	at net.minecraft.block.CactusBlock.func_196267_b(CactusBlock.java:45) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_196265_a(Block.java:434) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:vanillatweaks:drops}
	at com.lazynessmind.snad.common.block.SnadBlock.func_196265_a(SnadBlock.java:59) ~[?:1.14.4-1.7.11.10a] {re:classloading}
	at net.minecraft.block.BlockState.func_196944_b(BlockState.java:258) ~[?:?] {re:classloading,xf:fml:forgeendertech:randomTickBlock}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:466) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:405) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$10766/1188435723.accept(Unknown Source) ~[?:?] {}
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) ~[fastutil-8.2.1.jar:?] {}
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) ~[guava-21.0.jar:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:366) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:335) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:309) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95)
	at net.minecraft.block.CactusBlock.func_196267_b(CactusBlock.java:45)
	at net.minecraft.block.Block.func_196265_a(Block.java:434)
	at com.lazynessmind.snad.common.block.SnadBlock.func_196265_a(SnadBlock.java:59)
	at net.minecraft.block.BlockState.func_196944_b(BlockState.java:258)
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:466)
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:405)
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$10766/1188435723.accept(Unknown Source)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:366)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:335)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:309)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['ItsGuySmith'/228, l='Create Test Builds', x=-140.28, y=4.00, z=-247.79]]
	Chunk stats: ServerChunkCache: 2066
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Create Test Builds
	Level seed: 2579291777333200846
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-176,4,-208), Chunk: (at 0,0,0 in -11,-13; contains blocks -176,0,-208 to -161,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 149881 game time, 13000 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 29035 (now: false), thunder time: 29792 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 612838232 bytes (584 MB) / 2605187072 bytes (2484 MB) up to 3901751296 bytes (3721 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4186m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		AdditionalEnchantedMiner-1.14.4-14.1.8.jar QuarryPlus {quarryplus@14.1.8 DONE}
		AdvancedSkinCustomization-2.6.2.jar Advanced Skin Customization {advskinmod@2.6.2 DONE}
		Uppers-0.1.11.jar Uppers {uppers@0.1.11 DONE}
		ChineseWorkshop-1.14.4-2.4.1.jar ChineseWorkshop {chineseworkshop@2.4.1 DONE}
		ProjectE-1.14.4-PE1.0.1B.jar ProjectE {projecte@1.14.4-PE1.0.1B DONE}
		bambooeverything-1.14-1.5.0.jar Bamboo Everything {bambooeverything@1.14-1.5.0 DONE}
		rsgauges-1.14.4-1.2.2-b2.jar Gauges and Switches {rsgauges@1.2.2-b2 DONE}
		BowInfinityFix-1.14.4-rv7.1.jar Bow Infinity Fix {bowinfinityfix@rv7.1 DONE}
		Neat 1.5-19.jar Neat {neat@1.5-19 DONE}
		essentials-1.14.4-2.6.7.jar Essentials {essentials@1.14.4-2.6.7 DONE}
		BetterCaves-1.14.4-1.1.1.jar YUNG's Better Caves {bettercaves@1.14.4-1.1.1 DONE}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 DONE}
		ForgeEndertech-1.14.4-5.2.1.0-build.0076.jar Forge Endertech {forgeendertech@5.2.1.0 DONE}
		xnet-1.14-1.8.7-alpha.jar XNet {xnet@1.14-1.8.7-alpha DONE}
		XaerosWorldMap_1.5.5_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		JRFTL [1.14.4]-1.1.jar JRFTL {jrftl@1.1 DONE}
		CookingForBlockheads_1.14.4-7.4.4.jar Cooking for Blockheads {cookingforblockheads@7.4.4 DONE}
		Controlling-5.0.7.jar Controlling {controlling@5.0.6 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		Powah-1.14.4-0.2.8.jar Powah {powah@0.2.8 DONE}
		mightyarchitect-mc1.14.4_v0.5.jar The Mighty Architect {mightyarchitect@0.5 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		NomadicTents-1.14.4-10.1.0.jar Nomadic Tents {nomadictents@10.1.0 DONE}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 DONE}
		u_team_core-1.14.4-2.8.2.150.jar U Team Core {uteamcore@2.8.2.150 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		ForgivingVoid_1.14.4-3.0.8.jar Forgiving Void {forgivingvoid@3.0.8 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		snowvariants-1.14.4-1.1.1.jar Snow Variants {snowvariants@1.14.4-1.1.1 DONE}
		VTweaks-1.14.4-3.1.5.jar V-Tweaks {vtweaks@3.1.5 DONE}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 DONE}
		CarryOn MC1.14.4 v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 DONE}
		shetiphiancore-1.14-3.6.1.jar ShetiPhian-Core {shetiphiancore@3.6.1 DONE}
		mysticallib-1.14.4-1.14.0.jar Mystical Lib {mysticallib@1.14.4-1.14.0 DONE}
		absentbydesign-1.14.4-1.0.7.jar Absent By Design Mod {absentbydesign@1.14.4-1.0.7 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		quickhomes-1.14.4-1.2.4.2.jar QuickHomes {quickhomes@1.2.4.2 DONE}
		corpse-1.14.4-1.0.4.jar Corpse {corpse@1.14.4-1.0.4 DONE}
		useful_backpacks-1.14.4-1.7.6.60.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
		torchmaster-2.0.0-rc2.jar Torchmaster {torchmaster@2.0.0-rc2 DONE}
		embellishcraft-1.14.4-1.5.0.jar EmbellishCraft {embellishcraft@1.14.4-1.5.0 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BetterCrates-1.14.4-1.0.1.jar Better Crates {bettercrates@1.0.1 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		Lollipop-1.14.4-0.0.23.jar Lollipop {lollipop@0.0.23 DONE}
		adventurepack-1.2.jar Adventure Tools {adventurepack@1.14.4-1.2 DONE}
		SilentGear-1.14.4-1.4.6+72.jar Silent Gear {silentgear@1.4.6+72 DONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 DONE}
		simplylight-0.9.0.jar Simply Light {simplylight@0.9.0 DONE}
		simplefarming-1.14.4-1.2.8.jar Simple Farming {simplefarming@1.14.4-1.2.8 DONE}
		SolarFluxReborn-1.14.4-14.1.5.jar Solar Flux Reborn {solarflux@14.1.5 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		flying_things-1.8.5-1.14.4.jar The Flying Things {flying_things@1.8.5 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		cakechomps-FORGE-1.14.4-2.0.jar Cake Chomps {cakechomps@FORGE-1.14.4-2.0 DONE}
		extlights-1.8.jar Extended Lights {extlights@1.8 DONE}
		ClothConfig2-1.4.1.jar Cloth Config Forge v2 API {cloth-config2@1.4.1 DONE}
		BetterThanLlamas-1.14.4-1.1.0.jar Better Than Llamas {betterthanllamas@1.1.0 DONE}
		TorchBandolier-1.14.4-1.3.2+7.jar Torch Bandolier {torchbandolier@1.3.2+7 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		angelring-1.1.0.jar Angel Ring {angelring@1.1.0 DONE}
		libnonymous-1.14.4-1.0.4.25.jar Libnonymous {libnonymous@1.0.4.25 DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		malilib-forge-1.14.4-0.10.0-dev.19+alpha.2.jar MaLiLib {malilib@0.10.0-dev.19 DONE}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
		ChunkNoGoByeBye-1.14.4-1.0.3.jar ChunkNoGoByeBye {chunknogobyebye@1.14.4-1.0.3 DONE}
		furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		SBM-WoodenShears-1.14.4-1.0.0.jar SBM-Wooden Shears {woodenshears@1.0.0 DONE}
		YAMDA-4.1.1.jar YAMDA {yamda@4.1.1 DONE}
		bwncr-1.14.4-3.5.12.jar Bad Wither No Cookie Reloaded {bwncr@1.14.4-3.5.12 DONE}
		switchbow-1.5.8.jar Switch-Bow {switchbow@1.5.8 DONE}
		CleanView-1.15.2-v1.jar CleanView {cleanview@1.15.2-v1 DONE}
		lumberjack-2.0.0.jar LumberJack {lumberjack@2.0.0 DONE}
		BetterAdvancements-1.14.4-0.1.0.94.jar Better Advancements {betteradvancements@0.1.0.94 DONE}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		AdFinders-1.14.4-3.0.3.0-build.0078.jar Advanced Finders {adfinders@3.0.3.0 DONE}
		jmh_1.14.4-2.2.jar Just Mob Heads {jmh@2.2 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		TrashSlot_1.14.4-10.4.8.jar TrashSlot {trashslot@10.4.8 DONE}
		torchslabmod-1.14.4_v1.5.jar Torch Slab Mod {torchslabmod@1.5 DONE}
		EquipmentTooltips-1.14.4-1.3.2+10.jar Equipment Tooltips {equipmenttooltips@1.3.2+10 DONE}
		craftingstation-2.1.6.jar Crafting Station {craftingstation@2.1.6 DONE}
		snad-1.14.4-1.7.11.10a.jar Snad {snad@1.7.11.10a DONE}
		bountifulbaubles-1.14.4-0.0.2.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		BetterThanBunnies-1.14.4-1.2.0.jar Better Than Bunnies {betterthanbunnies@1.2.0 DONE}
		platforms-1.14-1.5.1.jar Platforms {platforms@1.5.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 DONE}
		EverlastingAbilities-1.14.4-1.6.0.jar EverlastingAbilities {everlastingabilities@1.6.0 DONE}
		cosmeticbeds-FORGE-1.14.4-2.0.0.1.jar Cosmetic Beds {cosmeticbeds@FORGE-1.14.4-2.0.0.1 DONE}
		caelus-FORGE-1.14.4-1.0.1.2.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.2 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		colytra-FORGE-1.14.4-2.1.0.jar Colytra {colytra@FORGE-1.14.4-2.1.0 DONE}
		extraboats-1.2.6-1.14.4.jar Extra Boats {extraboats@1.2.6 DONE}
		create-mc1.14.4_v0.2.3.jar Create {create@mc1.14-0.2.3 DONE}
		Clumps-4.0.1.jar Clumps {clumps@4.0.1 DONE}
		LightOverlay-3.6.2.jar Light Overlay Forge {lightoverlay-forge@3.6.2 DONE}
		comforts-FORGE-1.14.4-2.0-beta6.jar Comforts {comforts@FORGE-1.14.4-2.0-beta6 DONE}
		angelblock-1.0a.jar Angel Block {angelblock@1.0a DONE}
		decorative_blocks_6b.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		VanillaTweaks-1.14.4.1.5.12.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.12 DONE}
		RingOfTeleport-1.14.4-1.0.18.jar Ring of Teleport {ring_of_teleport@1.0.18 DONE}
		BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 DONE}
		The-Endergetic-Expansion-1.14.4-v1.2.0.jar The Endergetic Expansion {endergetic@1.2.0 DONE}
		demagnetize-1.14.4-1.2.1.jar Demagnetize {demagnetize@1.14.4-1.2.1 DONE}
		BonsaiTrees-2.0.2.35.jar Bonsai Trees 2 {bonsaitrees2@2.0.2.35 DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		JEITweaker-1.14.4-1.0.1.jar JEI Tweaker {jeitweaker@1.0.1 DONE}
		traverse-1.14.4-2.0.3.jar Traverse {traverse@1.14.4-2.0.3 DONE}
		mininggadgets-1.2.4.jar Mining Gadgets {mininggadgets@1.2.4 DONE}
		CraftTweaker-1.14.4-5.0.1.188.jar CraftTweaker {crafttweaker@5.0.1.188 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		ruins-1.14.4.6.jar Ruins {ruins@1.14.4.6 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		CraftingTweaks_1.14.4-10.2.1.jar Crafting Tweaks {craftingtweaks@10.2.1 DONE}
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		cofh_core-1.14.4-0.3.1b.jar CoFH Core {cofh_core@0.3.1b DONE}
		ensorcellation-1.14.4-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		Flopper-1.14.4-1.0.6.jar Flopper {flopper@1.0.6 DONE}
		itlt-1.14.4-1.0.2.jar It's the little things {itlt@1.14.4-1.0.2 DONE}
		EnchantmentDescriptions-1.14.4-1.3.14.jar EnchantmentDescriptions {enchdesc@1.3.14 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		paintings-1.14.4-6.0.1.5.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		Inspirations-1.14.4-1.0.2.jar Inspirations {inspirations@1.14.4-1.0.2 DONE}
		Xaeros_Minimap_20.4.0.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@20.4.0.1 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		StorageDrawers-1.14.4-6.0.7.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		DoubleSlabs-1.14-1.3.0.jar Double Slabs {doubleslabs@1.3.0 DONE}
		simplytea-2.0.4.jar Simply Tea {simplytea@2.0.4 DONE}
		PickleTweaks-1.14.4-3.0.7.jar Pickle Tweaks {pickletweaks@3.0.7 DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		RingOfAttraction-1.14.4-1.0.20.jar Ring of Attraction {ring_of_attraction@1.0.20 DONE}
		ilikewood-1.14.4-1.1.2.3.jar I Like Wood {ilikewood@1.1.2.3 DONE}
		SilentGems-1.14.4-3.4.8+81.jar Silent's Gems 3 {silentgems@3.4.8+81 DONE}
		FriendlyFire-1.14.4-3.0.2.jar FriendlyFire {friendlyfire@3.0.2 DONE}
		XL-Food-Mod-1.14.4-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		overloadedarmorbar-3.0.0b.jar Overloaded Armor Bar {overloadedarmorbar@3.0.0b DONE}
		xptome-1.14.4-v1.1.4.jar XP Tome {xpbook@v1.1.4 DONE}
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)

	Kiwi Modules: 
		chineseworkshop:blocks
		chineseworkshop:debug_stick
		chineseworkshop:decorations
		chineseworkshop:materials
		chineseworkshop:retexture
		kiwi:contributors
	Player Count: 1 / 8; [ServerPlayerEntity['ItsGuySmith'/228, l='Create Test Builds', x=-140.28, y=4.00, z=-247.79]]
	Data Packs: vanilla, mod:absentbydesign, mod:adfinders, mod:adventurepack, mod:advskinmod, mod:ambientsounds, mod:angelblock, mod:angelring, mod:appleskin, mod:arl, mod:bambooeverything, mod:betteradvancements (incompatible), mod:betteranimationscollection2, mod:bettercaves, mod:bettercrates, mod:betterthanbunnies, mod:betterthanllamas, mod:betterthanmending, mod:blur, mod:bonsaitrees2, mod:bountifulbaubles, mod:bowinfinityfix, mod:buildinggadgets, mod:bwncr, mod:caelus, mod:cakechomps, mod:carryon, mod:cfm, mod:chineseworkshop, mod:chunknogobyebye, mod:cleanview, mod:cloth-config2, mod:clumps, mod:cofh_core, mod:colytra, mod:comforts, mod:controlling, mod:cookingforblockheads, mod:corpse, mod:cosmeticbeds (incompatible), mod:craftingstation, mod:craftingtweaks, mod:crafttweaker, mod:create, mod:cucumber, mod:curios, mod:cyclopscore, mod:decorative_blocks, mod:demagnetize, mod:ding, mod:doubleslabs, mod:elevatorid, mod:embellishcraft, mod:enchdesc, mod:endergetic, mod:ensorcellation, mod:equipmenttooltips, mod:essentials, mod:everlastingabilities, mod:extcaves, mod:extlights, mod:extraboats, mod:fastbench, mod:fastfurnace, mod:fencejumper, mod:flopper, mod:flying_things, mod:forge, mod:forgeendertech, mod:forgivingvoid, mod:friendlyfire, mod:ftbbackups, mod:glassential, mod:ilikewood, mod:inspirations, mod:inventorysorter, mod:ironchest, mod:itlt, mod:jei, mod:jeitweaker, mod:jmh, mod:jrftl (incompatible), mod:kiwi, mod:libnonymous, mod:lightoverlay-forge, mod:lollipop, mod:lumberjack (incompatible), mod:malilib, mod:mantle, mod:mcjtylib, mod:metalbarrels, mod:mightyarchitect, mod:mininggadgets, mod:mousetweaks, mod:mysticallib, mod:neat, mod:nomadictents, mod:oreexcavation, mod:overloadedarmorbar, mod:paintings, mod:pickletweaks, mod:placebo, mod:platforms, mod:powah, mod:projecte, mod:quark, mod:quarryplus, mod:quickhomes, mod:refinedstorage, mod:refinedstorageaddons, mod:rftoolsbase, mod:ring_of_attraction, mod:ring_of_teleport, mod:rsgauges, mod:ruins, mod:shetiphiancore, mod:silentgear, mod:silentgems, mod:silentlib, mod:simplefarming, mod:simplylight, mod:simplytea, mod:snowvariants, mod:solarflux, mod:stonechest, mod:storagedrawers, mod:swingthroughgrass, mod:switchbow, mod:toastcontrol, mod:toolbelt, mod:torchbandolier, mod:torchmaster, mod:torchslabmod, mod:tramplestopper, mod:trashslot, mod:travellersboots, mod:traverse, mod:upgrade_aquatic, mod:uppers, mod:usefulbackpacks, mod:uteamcore, mod:vanillatweaks, mod:vtweaks, mod:waila, mod:woodenshears, mod:worldedit, mod:wstweaks, mod:xaerominimap, mod:xaeroworldmap, mod:xlfoodmod, mod:xnet, mod:xpbook, mod:yamda, mod:snad
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by lazynessmind** [comment]
oh, it looks like when the cactus pops off the game doesn´t realize that the cactus isn't there and tries to grow the air. Expect an updated today or tomorrow morning.
